#!/usr/bin/env bash

#set -x

#
# how to use compare-type1:
# $ scripts/compare-type1 baseline.csv input.csv output.csv 
#

baseline="$1"
input="$2"
output="$3"

echo -n "" > $output

for input_length in $(cat $baseline | cut -d, -f1 | sort -u -g)
do
  paste -d' ' \
    <(echo $input_length | sed -e 's/^ //') \
    <(cat $baseline | grep -E "^$input_length," | sort -g -t, -k2 | head -n6 | tail -n1 | cut -d',' -f2 | sed -e 's/^ //') \
    <(cat $input    | grep -E "^$input_length," | sort -g -t, -k2 | head -n6 | tail -n1 | cut -d',' -f2 | sed -e 's/^ //') |
  LC_ALL=C awk '{printf "%ld,%ld,%ld,%.02f\n", $1, $2, $3, (($3*100/$2)-100)}' >> $output

done

cat $output | \
LC_ALL=C awk 'BEGIN { FS = ","; sum = 0; } ; { sum+=$4; } ; END { print sum / NR }' > ${output/.csv/.avg}
