#!/usr/bin/env bash

#set -x

#
# how to use compare-type2:
# $ scripts/compare-type2 baseline.csv input.csv output.csv 
#

baseline="$1"
input="$2"
output="$3"

echo -n "" > $output

for output_length in $(cat $baseline | cut -d, -f1 | sort -u -g)
do
  for input_length in $(cat $baseline | cut -d, -f2 | sort -u -g)
  do
    paste -d' ' \
      <(echo $output_length | sed -e 's/^ //') \
      <(echo $input_length  | sed -e 's/^ //') \
      <(cat $baseline | grep -E "^$output_length, $input_length," | sort -g -t, -k3 | head -n6 | tail -n1 | cut -d',' -f3 | sed -e 's/^ //') \
      <(cat $input    | grep -E "^$output_length, $input_length," | sort -g -t, -k3 | head -n6 | tail -n1 | cut -d',' -f3 | sed -e 's/^ //') |
    LC_ALL=C awk '{printf "%ld,%ld,%ld,%ld,%.02f\n", $1, $2, $3, $4, (($4*100/$3)-100)}' >> $output
  done
done

cat $output | \
LC_ALL=C awk 'BEGIN { FS = ","; sum = 0; } ; { sum+=$5; } ; END { print sum / NR }' > ${output/.csv/.avg}
